spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.110.3.12:1521:tctest
    username: infodba
    password: infodba
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 9292
teamcenter:
  url: http://10.110.3.47:7010/tc
  user: admin
  pwd: admin
  fmsurl: http://10.110.3.47:4544
  fcccash: C:/temp
